name: Build LDView
on: [push, pull_request]
jobs:
  build-ubuntu:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install developement packages
        run:  sudo ./QT/docker/install-devel-packages.sh
      - name: Build LDView
        run: cd QT ; ./makedeb -qt5
  
  build-fedora:
    runs-on: ubuntu-22.04
    container:
      image: fedora:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install developement packages
        run:  sudo ./QT/docker/install-devel-packages.sh
      - name: Build LDView
        run:  cd QT ; mkdir -p ~/rpmbuild/{BUILD,RPMS,SOURCES,SPECS,SRPMS} ; ./makerpm

  build-windows:
    runs-on: windows-2019
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v2
      - name: Build LDView
        shell: cmd
        run: |
          .\build.cmd
          if not exist Build\Release64\LDView64.exe (
            echo "Build failed: Missing LDView64.exe"
            exit 1
          )

  build-windows-2022:
    runs-on: windows-2022
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v2
      - name: Build LDView
        shell: cmd
        run: |
          .\build.cmd
          if not exist Build\Release64\LDView64.exe (
            echo "Build failed: Missing LDView64.exe"
            exit 1
          )

  build-mac:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build LDView
        run: cd MacOSX/LDView ; xcodebuild
